### ISSUE TITLE
E78: unknown mark

### ISSUE THREAD

**Issue by ninrod** [machakann/vim-highlightedyank#1]
Hi, awesome idea for the plugin. I've just installed and it's working. Only thing is that I'm getting an annoying message on my echo area that says: 

`E78: Unknown mark`.

Would be nice if that does not appear at all. What you think?

**Comment by machakann** [comment]
Thank you for your report. Unfortunately I have left my house now, I will look for the reason in a few days.

Does that error message appear immediately when you press 'y' key? Could you reproduce the situation both in normal mode and in visual mode?

**Comment by ninrod** [comment]
No problem. Take your time. I'll try to reproduce when I get home.

**Comment by machakann** [comment]
Hi, I couldn't have reproduced the error message. Thus I'm not so sure, but I rewrite some doutful parts. Please give the latest version a try.

**Comment by ninrod** [comment]
Hi, so I could reproduce the behaviour. In visual mode it seems that a very fast error message appears and then disappears. In normal mode, I tried with `yiw` and the error message only appears when you press the `w`.

I'll see if I can get a ascii cinema cast.

**Comment by machakann** [comment]
Thank you, I guess you might have a keymapping like:

``` vim
noremap " '
```

Isn't it? Finally I found that old versions had 
problems with the setting, but it is fixed now.

**Comment by ninrod** [comment]
yes! here's exactly the mapping I use: [vimrc noremap snippet](https://github.com/ninrod/dotfiles/blob/master/dot/vimrc#L344-L347). Gonna test it now.

**Comment by machakann** [comment]
That's the very I expected! Hope the latest one works nice also for you.

**Comment by ninrod** [comment]
yes it is working nicely now. Thank you. I think we can close this.

**Comment by machakann** [comment]
Thanks!
