### ISSUE TITLE
Issues with unmodifiable buffer

### ISSUE THREAD

**Issue by firedev** [machakann/vim-highlightedyank#10]
When browsing git history with fugitive and accidentally copying stuff it blows up like this:

```
Error detected while processing function <SNR>156_wait_for_user_input[15]..<SNR>156_revert_highlight_fix:
line    5:
E21: Cannot make changes, 'modifiable' is off
```

**UPDATE**
Actually it was something else, I could not reproduce it reliably.

**Comment by machakann** [comment]
I'm not really sure what happened, but guessing from the error messeages it looks there is something trouble with [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors). Do you have any idea about it?

[s:wait_for_user_input()](https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L1163)
[s:revert_highlight_fix()](https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L1097)

**Comment by firedev** [comment]
I see, sorry about that. Didn't check where the error is originated. Will report it there.
