### ISSUE TITLE
Highlights are stuck all over the place

### ISSUE THREAD

**Issue by firedev** [machakann/vim-highlightedyank#11]
Hi, 

After the last update something happened and highlights are all over the screen, here are some errors I see fairly regularly:

```
Error detected while processing function highlightedyank#autocmd_highlight[10]..<SNR>170_highlight_yanked_region[10]..<SNR>170_glow[3]..highlightedyank#highlight#cancel[8]..<SNR>
171_scheduled_quench[4]..290[21]..<SNR>171_search_highlighted_windows[7]..<SNR>171_scan_windows[3]..<SNR>171_goto_window:
line   10:
E523: Not allowed here: 1wincmd w
Press ENTER or type command to continue
Error detected while processing function highlightedyank#autocmd_highlight[10]..<SNR>170_highlight_yanked_region[10]..<SNR>170_glow[3]..highlightedyank#highlight#cancel:
line    8:
E170: Missing :endfor
Press ENTER or type command to continue
Error detected while processing function highlightedyank#autocmd_highlight[10]..<SNR>170_highlight_yanked_region[10]..<SNR>170_glow:
line    3:
E171: Missing :endif
Press ENTER or type command to continue
```

Hope that helps.

**Comment by machakann** [comment]
Hi, thank you for your report!

Unfortunately I couldn't have reproduced the error, it might be a conflict with another plugin... I expect that a specific buffer or a keymapping cause the situation maybe, do you have any idea about that? Or if you can make a minimal vimrc, it is certain that the problem would be solved.

Let me think. I can make it a little better anyway, although it might not be the essential solution. Maybe.

**Comment by machakann** [comment]
I added a countermeasure. It may suppress the error message but the highlight might get slightly sticky sometimes, although It will be cleaned up in next time to edit texts.

**Comment by firedev** [comment]
Thanks, let's close this for now.

**Comment by machakann** [comment]
OK, finally I found out the way to reproduce. Now the problem has been solved, I guess. Please let me know in case you saw the error again.
