### ISSUE TITLE
Blockwise visual selection + $

### ISSUE THREAD

**Issue by ghost** [machakann/vim-highlightedyank#13]
Only the first column of visual selection is being highlighted when using blockwise visual mode + $ command. A combination of the same mode and ^ command works just fine.

nvim 0.1.7 + latest version of vim-highlightedyank (currently is 4354dac) with no configuration.

See demo for details:
https://asciinema.org/a/95387

**Comment by machakann** [comment]
Could you test the latest (16530e2)?

**Comment by ghost** [comment]
Yep, fixed. Thank you!

**Comment by machakann** [comment]
Thank you for your report!
