### ISSUE TITLE
Highlighting persists between different files

### ISSUE THREAD

**Issue by ghost** [machakann/vim-highlightedyank#14]
Demo:
https://asciinema.org/a/ccrwqztv1lfvgn96x19u1i3qv

Here I'm using <kbd>gf</kbd> and <kbd>Ctrl</kbd>-<kbd>O</kbd> commands for navigation between files, so don't get confused when screen text suddenly changes.

Same configuration: nvim 0.1.7 + latest version of vim-highlightedyank (16530e2)

**Comment by machakann** [comment]
Oops, I was too stupid. I thought highlightings were buffer local but actually they are window local.

**Comment by machakann** [comment]
OK, could you update to test 403003c?

**Comment by ghost** [comment]
Yes, it is working properly now. Nice work!

**Comment by machakann** [comment]
Thank you!
