### ISSUE TITLE
Highlighting of ruby method is broken

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-highlightedyank#15]
Hi!

I've just noticed, the highlighting stopped working with ba2194b83fe30c857813ca12802ab20beff6bb26
To test it, you'll need https://github.com/vim-ruby/vim-ruby

*Here is a module for tests:*
```ruby
module MyModule
  def my_method
    puts 'foo'
    puts 'bar'
  end
end
```
If you stay somewhere inside `my_method` and press <kbd>yam</kbd> (yank a method) or <kbd>yaM</kbd> (yank a module), the corresponding object will be yanked, but without any highlighting.
I can't get it work neither on neovim nor on vim.

**Comment by machakann** [comment]
Hi, sorry for my late response. I struggled to find a solution but it has been a tiny problem. Just one line correction, but I think it fixed the problem. Could you test it?

**Comment by sudo-nice** [comment]
Works fine here. Many thanks again! :man_dancing:
