### ISSUE TITLE
Dot doesn't repeat last yank

### ISSUE THREAD

**Issue by rafaeln** [machakann/vim-highlightedyank#17]
This is a great plugin. Thanks! I have had to deactivate it for the time being, though, because for some reason I can't use the dot command to repeat the previous yank.

**Comment by machakann** [comment]
Please try:

```
set cpo+=y
```

**Comment by machakann** [comment]
Ah, excuse me, it may not work properly. I will check it.

**Comment by machakann** [comment]
OK, now highlightedyank changes its behavior for dot repeat, depending on the `cpo-y` option as same as the default `y` command.

Please update and add the line into your vimrc to try.

```vim
set cpo+=y
```

**Comment by rafaeln** [comment]
That fixed it. Thanks!
