### ISSUE TITLE
Override/Select Highlight Colour?

### ISSUE THREAD

**Issue by Michael-Thibault** [machakann/vim-highlightedyank#18]
I'm using the Jellybeans colour scheme (current) in Neovim (0.1.7) and iTerm 2 (3.1.beta.2).

Would you consider an option to use a particular colour for the highlight, instead of ones from the colour scheme? If I yank a line of text that looks like this:

```vim
call dein#add('vim-highlightedyank')
```

...I see something of a rainbow (it's awfully garish).

Or perhaps using the visual mode highlighting instead? (It'd work nicely with Jellybeans at least. Haven't tried with others; I will if you bug me about it though. 😛 )

**Comment by machakann** [comment]
Hi, you can use a highlight group `HighlightedyankRegion` for the purpose. For example, if you want to use visual mode highlighting:

```vim
highlight link HighlightedyankRegion Visual
```

Or assign directly (see `:help :highlight`):

```vim
highlight HighlightedyankRegion ctermbg=237 guibg=#404040
```

---
This is optional but using autocmd is good idea. It works when you change colorscheme manually.

```vim
autocmd ColorScheme jellybeans highlight link HighlightedyankRegion Visual
```

**Comment by Michael-Thibault** [comment]
Ooooh, herpy derp derp. Well, this is what I get for being a vim newbie. :) Might be worth documenting that.

Thanks! 😄

**Comment by machakann** [comment]
Hahaha try `:help highlightedyank-highlight-groups`, or you can find something with `:help highlightedyank` and just scroll down!  😄 

But, indeed, put the example may be helpful, I will update later. Thanks!
