### ISSUE TITLE
Failed Motion Hangs

### ISSUE THREAD

**Issue by yarko3** [machakann/vim-highlightedyank#19]
Often, I will input a motion that cannot be executed in the specific context (like yi' instead of yi"). If the motion cannot be carried out, vim hangs. I hit esc or C-c to re-enter normal mode when this happens. I've been able to reproduce this in vim 8 and neovim.

My dotfiles are at yarko3/dotfiles.

**Comment by machakann** [comment]
Yes, actually this is known issue, and it is hard to avoid...

If you are using neovim, you don't need to make keymapping and then never hangs.
```vim
if !has('nvim')
    map y <Plug>(highlightedyank)
endif
```

As for vim, I need to wait for an auto-command event "TextYankPost" patch merged. Sorry.

**Comment by yarko3** [comment]
No worries; in the meantime, I'll try to get more accurate with my motions :D

**Comment by machakann** [comment]
The `TextYankPost` event has been merged! This problem will be solved in the latest Vim.
