### ISSUE TITLE
unexpected cursor jump in normal mode

### ISSUE THREAD

**Issue by ninrod** [machakann/vim-highlightedyank#2]
I have the following line in vim, right now:

``` txt
two words.
--------^ (cursor here)
```

if I type, `y` the expected behaviour would be this:

``` txt
two words.
----^---- (cursor here)
```

instead, what I get is this:

``` txt
two words.
^-------- (cursor here)
```

**Comment by machakann** [comment]
Sorry for my late reply, do you still get this error?

**Comment by ninrod** [comment]
Hi.

no. Something changed in the last release that fixed this behaviour. You can safely close this. thanks.

**Comment by machakann** [comment]
OK! Probably something related to #1. Thanks!
