### ISSUE TITLE
Ctrl-P window closes when yank highlight timer expires

### ISSUE THREAD

**Issue by tbodt** [machakann/vim-highlightedyank#22]
Steps to repro:

  - Install ctrlp and highlightedyank.
  - Yank something and then immediately press ctrl-p.
  - Observe that the ctrlp window vanishes when the yank highlight goes away.

**Comment by machakann** [comment]
Thank you for your report! I've just pushed the commit fixing the problem. Please give it a try to update.

**Comment by tbodt** [comment]
All is fixed! Thanks
