### ISSUE TITLE
No such group or event: OptionSet cpoptions call s:keymap()

### ISSUE THREAD

**Issue by wookayin** [machakann/vim-highlightedyank#23]
I know it is a vim version issue, but am reporting this issue for others' references.

Error message:
```
Error detected while processing ~/.vim/plugged/vim-highlightedyank/plugin/highlightedyank.vim:
line   52:
E216: No such group or event: OptionSet cpoptions call s:keymap()
```

The `OptionSet` autocmd event was introduced in Vim 7.4.786, hence the minimum vim version. I think it would be great to include this version requirement in README.md, for instance.

**Comment by machakann** [comment]
Hi! Sorry for my late response. Finally, I made it work with old vims, though it could not behave perfectly as same as the latest vim. At least, you may not see the error message with Vim 7.4.786. Thanks!

**Comment by wookayin** [comment]
Great, thanks!

**Comment by wookayin** [comment]
(A side note) `exist('##OptionSet')` will be useful for users to test vim compatibility.
