### ISSUE TITLE
Difference with vim-operator-flashy?

### ISSUE THREAD

**Issue by Asheq** [machakann/vim-highlightedyank#27]
I'm trying to decide between using this and [vim-operator-flashy](https://github.com/haya14busa/vim-operator-flashy)? They both seem to work great.

I'm curious what your take is on the differences in features and quality.

**Comment by machakann** [comment]
vim-operator-flashy is an operator, thus it works perfect with motions and textobjects, but no way to avoid being repeated by dot command. vim-highlightedyank is not an operator, thus it has a little problem with wrong input (#19), but it is not dot-repeated.

Both of those weak points may be solved in future. For example, as for the vim-highlightedyank, #19 is solved by using `TextYankPost` autocommand event [which is currently discussed](vim/vim#2333), this event is already available with neovim.

**Comment by machakann** [comment]
`TextYankPost` event also makes this plugin free from any keymappings. With the event, a user does not need to add any keymapping settings to his vimrc.

**Comment by Asheq** [comment]
I see, thanks for the response! Good luck withe the `TextYankPost` event. I'll go ahead and close this now.
