### ISSUE TITLE
Visual selection highlighted upon leaving visual mode

### ISSUE THREAD

**Issue by olmokramer** [machakann/vim-highlightedyank#28]
Hi, thanks for this nifty plugin :)

When I leave visual mode with `<Esc>`, the text that was selected is briefly highlighted with the same colors as the highlightedyank highlight. When I disable the plugin it's gone. The plugin still seems to work fine otherwise. I'm on Vim version 8.0, patch 1415, so I do not have a `<Plug>(highlightedyank)` mapping anymore, but rely on the `TextYankPost` event.

**Comment by machakann** [comment]
Hi, I'm not so sure the reason at this moment. I haven't seen such a case. But, probably, it may be a kind of conflict with another plugin. Some plugins use yank command internally; this action also triggers the `TextYnakPost` event. It is impossible to distinguish the event sent by a plugin or by a user. 

I would like to ask you that:
  1. Is it 100% reproduced when you exit visual mode?
  2. Any mapping for `<Esc>` key? You can check `:verbose xmap <Esc>`
  3. If you wouldn't mind, could you show me the list of plugins you are using? Or just try to check with dropping other plugins one-by-one.

**Comment by olmokramer** [comment]
Ok, I found the issue. It had to do with my `'clipboard'` option, which apparently defaults to `autoselect` in an Xorg environment. It yanks all selected text to the `"*` register, which in turn causes a `TextYankPost` event. When I `set clipboard-=autoselect` in my vimrc the highlighting is gone.

**Comment by urxvtcd** [comment]
I too am experiencing this issue even on vanilla vim and disabling `autoselect` doesn't seem to work.
Steps to reproduce:

```
gvim -u NONE -U NONE
```
enter few lines of random text, then type `yy` to yank a single line, go to some other line, enter visual mode, and exit it. The yanked line gets highlighted.

For some reason, ancient I has applied this patch that makes this issue go away. Don't remember where it came from.

```diff
diff --git a/autoload/highlightedyank.vim b/autoload/highlightedyank.vim
index d63817c..8153929 100644
--- a/autoload/highlightedyank.vim
+++ b/autoload/highlightedyank.vim
@@ -39,6 +39,10 @@ function! highlightedyank#debounce() abort "{{{
     call timer_stop(s:timer)
   endif

+  if v:event.operator != 'y' || v:event.regname ==# '*'
+    return
+  endif
+
   " NOTE: The timer callback is not called while vim is busy, thus the
   "       highlight procedure starts after the control is returned to the user.
   "       This makes complex-repeat faster because the highlight doesn't
```
