### ISSUE TITLE
<Ctrl-v> is not work

### ISSUE THREAD

**Issue by qianlei90** [machakann/vim-highlightedyank#29]
The demo section in README shows that this plugin supports blockwise-visual mode, but it doesn't work with neovim v0.2.3. I saw 'FIXME' in autoload/highlightedyank.vim, seems that the demo picture is not right.

**Comment by machakann** [comment]
Thank you, you are right. It seems I made a mistake in e1ed3124ecd7447dd73529babb3c261e12fbfb7c. The problem is fixed in the latest commit now. Please test it.

**Comment by qianlei90** [comment]
It works perfect for me. Thanks for your work.
