### ISSUE TITLE
leave the yank register untouched

### ISSUE THREAD

**Issue by ninrod** [machakann/vim-highlightedyank#3]
Hi again.

This plugin is sequestering the `"0` register, a.k.a., the `yank register`.

I think it is in the user's best interest if the `yank register` is left unharmed.

to reproduce, just yank a word and check the registers with `:reg`. 

With the plugin loaded, the `"0` register is not updated with the yanked content. 

With the plugin not loaded, the `"0` register functions as expected and it is updated with the yanked content.

**Comment by machakann** [comment]
Yes, I totally agree with you! Thanks, I felt something strange these days but I didn't aware of the reason. Probably this is fixed now, please give it a try with the latest.

**Comment by ninrod** [comment]
That was fast. Yes, we can safely close now. Thank you.
