### ISSUE TITLE
Feature Request: Support for highlighting pasted text

### ISSUE THREAD

**Issue by ratheesh** [machakann/vim-highlightedyank#30]
Is it possible to add an option for highlighting pasted text? I would be nice to this functionality.

**Comment by machakann** [comment]
It may be out of the scope of this plugin, but fortunately, I remember someone else has done such kind of work.

[vim-shiny](https://github.com/MaxMEllon/vim-shiny)

Why don't you try this?

**Comment by ratheesh** [comment]
I did not see that before. vim-shiny works for me. 
Thank you.
