### ISSUE TITLE
Screen flashes and looses visual selection when switching tab

### ISSUE THREAD

**Issue by copy** [machakann/vim-highlightedyank#32]
For testing, set `highlightedyank_highlight_duration` to a high value, for example:

```
let g:highlightedyank_highlight_duration = 10000
```

Then:

- Open two tabs with some text
- Select and yank some text in the first tab
- Switch to the second tab and select some text
- Wait until the highlight duration ends
- Observe that the screen flashes and the selection in the second tab is lost

Tested with the latest master version of vim-highlightedyank and neovim v0.2.2.

**Comment by machakann** [comment]
Thank you for your report. That's because vim-highlightedyank moved the cursor to another tab to delete highlights, probably. I think it is not so reasonable to keep the highlight in another tab, so I will change it as the highlight will be cleared immediately when a user switches tab windows.

**Comment by machakann** [comment]
I pushed a fix for this problem. Please update vim-highlightedyank and test it.

**Comment by copy** [comment]
Can confirm this is fixed. Cheers!
