### ISSUE TITLE
highlighted yank does not work for some color scheme?

### ISSUE THREAD

**Issue by jdhao** [machakann/vim-highlightedyank#36]
I found that for some colorscheme, highlighted yank does not work.  If I use [vim-sublime-monokai](https://github.com/ErichDonGubler/vim-sublime-monokai), the highlight does not work. If I change the colorscheme to [gruvbox](https://github.com/morhetz/gruvbox), now the highlight works. 

Settings for highlightedyank is:
```
hi HighlightedyankRegion cterm=reverse gui=reverse
let g:highlightedyank_highlight_duration = 500
```

**Comment by machakann** [comment]
vim-highlightedyank uses `IncSearch` highlight group by default. However it seems vim-sublime-monokai doesn't set the `IncSearch` group. Probably that's why the reason. I think the easiest solution is to add the following lines into your vimrc:

```vim
augroup vimrc-highlightedyank
  autocmd ColorScheme sublimemonokai highlight HighlightedyankRegion ctermbg=237 guibg=#41423a
augroup END
```

Please change augroup name and the colors as you prefer.

**Comment by machakann** [comment]
By the way, in my case vim-highlightedyank just worked with the line:

```vim
hi HighlightedyankRegion cterm=reverse gui=reverse
```

You may need to check whether the setting is really taking effect, for example, type `:verbose hi HighlightedyankRegion<CR>`. I guess `HighlightedyankRegion` may be cleared or overwritten somewhere. Locating the line after `:colorscheme` setting in vimrc may help.

**Comment by jdhao** [comment]
Thanks, it works now. For anyone interested, you can find the supported color using the script [here](http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim).
