### ISSUE TITLE
Cannot yank visual selection to system clipboard

### ISSUE THREAD

**Issue by Snaptags** [machakann/vim-highlightedyank#4]
When the <Plug>(highlightedyank) mapping is active I cannot yank a **visual selection** to the system clipboard using "+y

(using gvim 7.4.1023 and Windows 8.1)

**Comment by machakann** [comment]
Thank you for your report!
I found a bug and it has been fixed now, but I'm not really sure whether it solved the problem or not... Could you give it a try with the latest version?

**Comment by Snaptags** [comment]
I tried the latest version on two Windows machines: everything is working fine now! Thank you for the fix, now the plugin is really great!
