### ISSUE TITLE
Stuck when highlighting and switch window back and forth

### ISSUE THREAD

**Issue by bootleq** [machakann/vim-highlightedyank#41]
Hi, when highlight is on, I found sometimes the cursor stop to response.

Can be reproduced with below vimrc:
```
set all&
set nocompatible
set runtimepath=
language messages POSIX

set rtp+=path/to/vim-highlightedyank/
let g:highlightedyank_highlight_duration = -1
```

Then start Vim with `vim -u above.vimrc above.vimrc above.vimrc -d` (I mostly encounter this issue in diff mode)
and do
```
yy
<C-W>l
<C-W>t
<C-W>l
<C-W>t
```

The screen seems stuck and must use `<Ctrl-C>` to get back control.

Vim version: 8.2.0148

**Comment by machakann** [comment]
Thank you for your report. I probably fixed the problem. Feel free to re-open if the same or similar problem appeared.

**Comment by bootleq** [comment]
Confirmed fixed, thank you very much.
