### ISSUE TITLE
Yank in neovim terminal

### ISSUE THREAD

**Issue by incoggnito** [machakann/vim-highlightedyank#42]
Hello,
i'm not sure if it's possible to add the highlightedyank to the neovim terminal.
I would love it.

**Comment by machakann** [comment]
Hi, I'm not sure whether I understood your question. Do you want to yank a text with the highlight in a terminal window? If so, it would just work as in normal windows.

![highlightedyank_nvim_terminal](https://user-images.githubusercontent.com/480049/76160478-8473e380-6165-11ea-892f-211908d60682.gif)

**Comment by incoggnito** [comment]
Sry, for late reply. I guess i had a bug in my nvim configuration. Now it works.

**Comment by machakann** [comment]
Ok, good to hear that! Please reopen if you got the same problem again.
