### ISSUE TITLE
program name

### ISSUE THREAD

**Issue by dalohuer2004** [machakann/vim-highlightedyank#46]
Hi, sorry for the inconvenience, I just want to know the name of this app please:

https://camo.githubusercontent.com/3fc438b068ede98cf3197fa402e4cd2a669eb8f0c7448f24406870396cd06eaa/687474703a2f2f692e696d6775722e636f6d2f48756c795a366e2e676966

thank you very much.

**Comment by machakann** [comment]
Did you mean the software visualizing my key sequences? If so, [KeyCastOW](https://github.com/brookhong/KeyCastOW)

**Comment by dalohuer2004** [comment]
thank you very much, I thought it was also for linux, I'll keep looking. Very kind.
