### ISSUE TITLE
Neovim's built-in highlighting?

### ISSUE THREAD

**Issue by mb720** [machakann/vim-highlightedyank#49]
Hi and thanks a lot for your plugin!

In Neovim's `:h feature-compile` I just read:

    Some features are built in that otherwise required external plugins: Highlighting the yanked region, see |lua-highlight|.

Does this mean I can have yank highlighting without using this plugin? With Neovim's default configuration, I don't see any highlighting after yanking text.

**Comment by polyzen** [comment]
```
vim.cmd([[
  augroup highlight_yank
    autocmd!
    autocmd TextYankPost * silent! lua vim.highlight.on_yank()
  augroup END
]])
```

https://github.com/neovim/neovim/blob/287d3566de11f82aa86448998fd4703b1db328bd/runtime/doc/lua.txt#L572

**Comment by mb720** [comment]
Thanks for the pointer. [Here's](https://neovim.io/doc/user/lua.html#lua-highlight) another link to the documentation. I settled for this in my `init.vim`:

    augroup highlight_yank
      autocmd!
      autocmd TextYankPost * silent! lua vim.highlight.on_yank {timeout=300}
    augroup END
