### ISSUE TITLE
Paste only 1st line of visual yanked selection

### ISSUE THREAD

**Issue by KabbAmine** [machakann/vim-highlightedyank#5]
- Make a selection in visual mode.
- Yank it.
- Paste it.

Only an empty line + 1st line of our selection will be pasted.

![hy](https://cloud.githubusercontent.com/assets/5658084/17726814/2c358340-6466-11e6-83f7-f9e6ecfaeb33.gif)

The issue occurs on both gvim and terminal vim (v7.4.1689), and it started after last commits (I didn't investigate yet, but I'm sure that this behavior wasn't present a few days ago)

It may be related to #4

_P.S:_ Thanks for your wonderful pugin

**Comment by machakann** [comment]
That was so careless mistake in a commit pushed last night. Thank you for your report!
