### ISSUE TITLE
E120: Using <SID> not in a script context: s:highlight

### ISSUE THREAD

**Issue by xfzv** [machakann/vim-highlightedyank#52]
After updating to https://github.com/machakann/vim-highlightedyank/commit/03fe057c5836a3f3897a943dc96bdfe3f087890e, I'm no longer getting the highlighting effect and the following error is printed every time: `E120: Using <SID> not in a script context: s:highlight`.

```
nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

I'm using [Lazy](https://github.com/folke/lazy.nvim) as package manager and load `vim-highlightedyank` with:

```lua
return {
	"machakann/vim-highlightedyank",
}
```

I don't know why but the issue persists even when sticking to https://github.com/machakann/vim-highlightedyank/commit/f9db473137ca96c6a989ec3e2b7edf8a3189c448 with:

```lua
return {
	"machakann/vim-highlightedyank",
	commit = "f9db473137ca96c6a989ec3e2b7edf8a3189c448",
}
```

The issue is solved only if I completely disable the plug-in:

```lua
return {
	"machakann/vim-highlightedyank",
	enabled = false,
}
```

**Comment by machakann** [comment]
Maybe, it is fixed at the latest now. Could you test?

**Comment by machakann** [comment]
Thanks!

**Comment by xfzv** [comment]
Can confirm https://github.com/machakann/vim-highlightedyank/commit/fa3f57b097e9521ce41a66b6c7cf5d9adea70ea3 fixed the issue.

Thanks.
