### ISSUE TITLE
Open terminal popup window swiftly enough before highlight is deleted will cause E863 error

### ISSUE THREAD

**Issue by jiz4oh** [machakann/vim-highlightedyank#56]
Hi @machakann, I occurred the error `E863: Not allowed for a terminal in a popup window` after I swatch to a terminal popup window before highlight is deleted. There is the error description of `E863`

![image](https://github.com/machakann/vim-highlightedyank/assets/41264693/492d1557-620f-42c5-b1d4-f69207ad2230)

And I located the source is [here](https://github.com/machakann/vim-highlightedyank/blob/fa3f57b097e9521ce41a66b6c7cf5d9adea70ea3/autoload/highlightedyank/highlight.vim#L260). It appears that the deletion process is asynchronous. If I open the Popup window swiftly enough, the deletion process tends to fail.

**Comment by machakann** [comment]
Thank you for your detailed report! Probably, the problem has been solved in the latest version. Please update.

**Comment by jiz4oh** [comment]
Confirmed. Thanks for your quick fix
