### ISSUE TITLE
$C causes error

### ISSUE THREAD

**Issue by firedev** [machakann/vim-highlightedyank#9]
```
Error detected while processing function highlightedyank#autocmd_highlight:
line   25:
highlightedyank: Unanticipated error. [function highlightedyank#autocmd_highlight[17]..<SNR>186_glow[3]..highlightedyank#highlight#cancel[8]..<SNR>187_scheduled_quench[4]..341[21]..<SNR>187_search_highlighted_windows[7]..<SNR>187_scan_windows[3]..<SNR>187_goto_window, line 10] Vim(wincmd):E523: Not allowed here: 1win
cmd w
Press ENTER or type command to continue
```

**Comment by firedev** [comment]
Actually it might be something else, once it's started, it errors on everything it seems. Not sure what happened, but I have some highlights stuck inside the code.

**Comment by machakann** [comment]
I'm not really sure but I guess it may happen when using **c** operator and immediately completion pop-up window appearing.  Probably it is not expected to work this plugin other than with **y** operator, so I add a safety to prevent the situations. Could you update and monitor if the error appears again or not?

**Comment by firedev** [comment]
Thanks, looks fine! I'll reopen if something blows up.
